import type {
  AnalysisResult,
  AppCase,
} from "./types";

export const cases: AppCase[] = [
  {
    id: "case-wifi",
    title: "Wi-Fi disconnects every 10–15 minutes after Windows update",
    category: "Network & Wi-Fi",
    status: "Monitoring",
    severity: "High",
    symptom: "Network adapter resets intermittently; Wi-Fi drops every 10–15 min since last Windows update.",
    description:
      "Dell XPS 15 on Windows 11. After the recent cumulative update the Intel Wi-Fi driver was refreshed and the adapter now resets every 10–15 minutes — usually during video calls. Other devices on the same network stay connected.",
    environment: {
      os: "Windows 11",
      device: "Dell XPS 15",
      version: "23H2",
      recentChange: "Intel Wi-Fi driver updated by Windows Update",
    },
    tags: ["Windows 11", "Intel Wi-Fi", "driver regression"],
    createdAt: "3d ago",
    updatedAt: "2h ago",
    confidence: 96,
    successRate: 82,
    matchedCases: 1842,
    selectedFixId: "fix-wifi-1",
    selectedFixTitle: "Rollback Intel Wi-Fi Driver",
    stepsDone: 5,
    stepsTotal: 5,
    reward: 8,
    rewardStatus: "pending",
    evidence: ["text", "log"],
    outcome: "resolved",
    verificationConfidence: 96,
    observation: { timeLabel: "18h / 24h", hoursElapsed: 18, hoursTotal: 24, complete: false },
    contributor: "Alex Morgan",
    contributorInitials: "AM",
    fixes: [
      {
        id: "fix-wifi-1",
        rank: 1,
        title: "Rollback Intel Wi-Fi Driver",
        why: "The update pulled a regression for the AX210 family. Rolling back to the previous Intel driver removes the adapter reset signature.",
        successRate: 82,
        matchScore: 94,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "5 minutes",
        steps: [
          "Open Device Manager → Network adapters → Intel Wi-Fi",
          "Properties → Driver → Roll Back Driver",
          "Reboot and reconnect to the network",
          "Observe connection stability for 10 minutes",
        ],
        category: "Network & Wi-Fi",
        tags: ["driver", "rollback", "intel"],
        verifiedCases: 1511,
        isTopPicked: true,
      },
      {
        id: "fix-wifi-2",
        rank: 2,
        title: "Network Adapter Reset",
        why: "Clears corrupted adapter state carried over from the update. Lower success (47%) but zero risk.",
        successRate: 47,
        matchScore: 71,
        confidence: "Medium",
        risk: "Low",
        effort: "Low",
        estimatedTime: "4 minutes",
        steps: [
          "Settings → Network & Internet → Advanced network settings",
          "Network reset → Reset now",
          "Reconnect and re-enter Wi-Fi password",
        ],
        category: "Network & Wi-Fi",
        tags: ["network", "reset"],
        verifiedCases: 866,
      },
      {
        id: "fix-wifi-3",
        rank: 3,
        title: "DNS Configuration Change",
        why: "Rare fit (12%) but cheap to try when the driver path has been exhausted.",
        successRate: 12,
        matchScore: 22,
        confidence: "Low",
        risk: "Medium",
        effort: "Medium",
        estimatedTime: "6 minutes",
        steps: [
          "Open adapter properties → IPv4 → Properties",
          "Set DNS to 1.1.1.1 and 1.0.0.1",
          "Flush DNS: ipconfig /flushdns",
        ],
        category: "Network & Wi-Fi",
        tags: ["dns", "troubleshoot"],
        verifiedCases: 221,
      },
    ],
    reasoning: [
      { cause: "Intel Wi-Fi driver regression introduced by the update", likelihood: 94 },
      { cause: "Adapter power management trimming radio power", likelihood: 41 },
      { cause: "IPv6 + DHCP lease churn on the adapter", likelihood: 18 },
    ],
    similarCases: [
      { title: "Intel AX210 disconnects after cumulative update", category: "Network & Wi-Fi", match: 96, outcome: "Verified" },
      { title: "AX211 adapter resets during Teams calls", category: "Network & Wi-Fi", match: 89, outcome: "Verified" },
      { title: "Windows 11 drops Wi-Fi ~15 min after reboot", category: "Network & Wi-Fi", match: 83, outcome: "Partially Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "Wi-Fi disconnect + adapter reset after update", time: "3d ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "1,842 similar cases matched", time: "3d ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Rollback Intel Wi-Fi Driver", time: "3d ago", tone: "info" },
      { id: "t4", label: "Fix attempted", detail: "Driver rolled back — connection stable", time: "1d ago", tone: "violet" },
      { id: "t5", label: "Evidence submitted", detail: "Recurrence log + adapter uptime", time: "1d ago", tone: "neutral" },
      { id: "t6", label: "Monitoring outcome", detail: "Observation window 18h / 24h", time: "2h ago", tone: "warning" },
    ],
  },
  {
    id: "case-hydration",
    title: "React hydration mismatch caused by client-only timestamp",
    category: "Coding Error",
    status: "Verified",
    severity: "Medium",
    symptom: "Next.js warns about hydration mismatch and the timestamp flickers after load.",
    description:
      "A dashboard header renders `new Date().toLocaleTimeString()` directly in the JSX. Server HTML contains one time, client re-renders with another — React logs a hydration mismatch and the time visibly changes after load.",
    environment: {
      os: "Windows 11",
      device: "Development PC",
      version: "Next.js 15",
      recentChange: "Added live clock to dashboard header",
    },
    tags: ["React", "Next.js", "hydration"],
    createdAt: "1w ago",
    updatedAt: "4d ago",
    confidence: 96,
    successRate: 91,
    matchedCases: 487,
    selectedFixId: "fix-hydration-1",
    selectedFixTitle: "Render timestamps client-side only",
    stepsDone: 4,
    stepsTotal: 4,
    reward: 8,
    rewardStatus: "claimable",
    evidence: ["code", "output"],
    outcome: "resolved",
    verificationConfidence: 96,
    contributor: "Alex Morgan",
    contributorInitials: "AM",
    fixes: [
      {
        id: "fix-hydration-1",
        rank: 1,
        title: "Render timestamps client-side only",
        why: "Dates derived from the client clock can never match server HTML. Mount the value inside useEffect (or a client-only flag) so SSR renders a stable placeholder.",
        successRate: 91,
        matchScore: 93,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "5 minutes",
        steps: [
          "Wrap the timestamp in a client component",
          "Render a stable placeholder during SSR (e.g. em-dash)",
          "Set the real time in useEffect / useSyncExternalStore",
        ],
        category: "Coding Error",
        tags: ["react", "hydration", "ssr"],
        verifiedCases: 443,
        isTopPicked: true,
      },
      {
        id: "fix-hydration-2",
        rank: 2,
        title: "Use suppressHydrationWarning on the leaf node",
        why: "Silences the warning when the diff is intentional and harmless — but only on the exact leaf element.",
        successRate: 58,
        matchScore: 44,
        confidence: "Medium",
        risk: "Low",
        effort: "Low",
        estimatedTime: "2 minutes",
        steps: [
          "Find the exact element that renders the time",
          "Add suppressHydrationWarning to that element only",
        ],
        category: "Coding Error",
        tags: ["react", "hydration"],
        verifiedCases: 282,
      },
      {
        id: "fix-hydration-3",
        rank: 3,
        title: "Derive time from a stable SSR context",
        why: "Serve an identical timestamp on both sides via a server-value context so output matches exactly.",
        successRate: 41,
        matchScore: 28,
        confidence: "Low",
        risk: "Medium",
        effort: "Medium",
        estimatedTime: "15 minutes",
        steps: [
          "Compute the time once in a server component",
          "Pass through props/context to the client component",
        ],
        category: "Coding Error",
        tags: ["react", "ssr", "context"],
        verifiedCases: 199,
      },
    ],
    reasoning: [
      { cause: "Client-only timestamp differs between server and client render", likelihood: 96 },
      { cause: "Browser extension mutating the DOM before hydration", likelihood: 7 },
      { cause: "Locale/timezone mismatch in rendering config", likelihood: 4 },
    ],
    similarCases: [
      { title: "Hydration mismatch on date-fns formatted dates", category: "Coding Error", match: 92, outcome: "Verified" },
      { title: "Clock flicker in dashboard header (Next.js)", category: "Coding Error", match: 88, outcome: "Verified" },
      { title: "Text mismatch after SSR + client mount", category: "Coding Error", match: 81, outcome: "Partially Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "Hydration mismatch warning + clock flicker", time: "1w ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "487 similar cases matched", time: "1w ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Render timestamps client-side only", time: "1w ago", tone: "info" },
      { id: "t4", label: "Fix attempted", detail: "Clock moved into a mounted client component", time: "5d ago", tone: "violet" },
      { id: "t5", label: "Evidence submitted", detail: "Diff + clean build output", time: "5d ago", tone: "neutral" },
      { id: "t6", label: "Outcome verified", detail: "No mismatch after 48h — +8 FIX earned", time: "4d ago", tone: "success" },
    ],
  },
  {
    id: "case-xlookup",
    title: "Excel XLOOKUP returning #N/A for existing values",
    category: "Apps & Productivity",
    status: "Suggested",
    severity: "Medium",
    symptom: "XLOOKUP returns #N/A even when the lookup value clearly exists.",
    description:
      "Spreadsheet uses XLOOKUP against a filtered range. Values exist but the function refuses to resolve — usually a mismatch between lookup_vector and return_array shapes.",
    environment: {
      os: "Windows 11",
      device: "Office PC",
      version: "Microsoft 365 · Excel 2024",
    },
    tags: ["Excel", "XLOOKUP", "#N/A"],
    createdAt: "6h ago",
    updatedAt: "6h ago",
    confidence: 88,
    successRate: 74,
    matchedCases: 612,
    selectedFixId: null,
    stepsDone: 0,
    stepsTotal: 3,
    reward: 6,
    rewardStatus: "none",
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-xlookup-1",
        rank: 1,
        title: "Match lookup_vector and return_array spans",
        why: "XLOOKUP requires both ranges to start on the same row. A one-row offset returns #N/A for everything.",
        successRate: 74,
        matchScore: 86,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "3 minutes",
        steps: [
          "Confirm lookup_vector and return_array start on the same row",
          "Rewrite ranges with identical anchors (e.g. $B:$B, $C:$C)",
          "Re-test with a static value in the lookup_vector",
        ],
        category: "Apps & Productivity",
        tags: ["excel", "xlookup"],
        verifiedCases: 452,
        isTopPicked: true,
      },
      {
        id: "fix-xlookup-2",
        rank: 2,
        title: "Convert to table references or remove structured refs",
        why: "Structured references inside filtered rows can silently shift the match window.",
        successRate: 51,
        matchScore: 39,
        confidence: "Medium",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "8 minutes",
        steps: [
          "Replace structured @[Column] refs with absolute ranges",
          "Verify the lookup column has no leading/trailing spaces",
        ],
        category: "Apps & Productivity",
        tags: ["excel", "tables"],
        verifiedCases: 311,
      },
      {
        id: "fix-xlookup-3",
        rank: 3,
        title: "Wrap with IFERROR + trim cleanup",
        why: "Cosmetic mitigation that keeps the workbook usable while the write-up is verified.",
        successRate: 22,
        matchScore: 14,
        confidence: "Low",
        risk: "Low",
        effort: "Low",
        estimatedTime: "2 minutes",
        steps: [
          "Wrap formula: IFERROR(XLOOKUP(...), \"missing\")",
          "Add TRIM on both sides to strip invisible whitespace",
        ],
        category: "Apps & Productivity",
        tags: ["excel", "iferror"],
        verifiedCases: 134,
      },
    ],
    reasoning: [
      { cause: "lookup_vector and return_array ranges are offset", likelihood: 86 },
      { cause: "Text values contain invisible whitespace or different types cells", likelihood: 39 },
      { cause: "XLOOKUP search_mode with unsorted data", likelihood: 11 },
    ],
    similarCases: [
      { title: "XLOOKUP #N/A after hiding helper column", category: "Apps & Productivity", match: 82, outcome: "Verified" },
      { title: "VLOOKUP vs XLOOKUP range anchor drift", category: "Apps & Productivity", match: 76, outcome: "Partially Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "XLOOKUP returns #N/A for existing values", time: "6h ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "612 similar cases matched", time: "6h ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Top pick: match range spans", time: "6h ago", tone: "info" },
    ],
  },
  {
    id: "case-module",
    title: "Python ModuleNotFoundError after 'pip install' succeeded",
    category: "Coding Error",
    status: "Verified",
    severity: "Medium",
    symptom: "Import fails in VS Code although pip install output reported success.",
    description:
      "Python 3.12 + venv. `pip install requests` completes, but the script raises ModuleNotFoundError when run from VS Code. Classic interpreter mismatch between the shell and the editor.",
    environment: {
      os: "Windows 11",
      device: "Laptop",
      version: "Python 3.12",
      recentChange: "Created a new virtual environment",
    },
    tags: ["Python", "pip", "venv", "VS Code"],
    createdAt: "2w ago",
    updatedAt: "1w ago",
    confidence: 97,
    successRate: 95,
    matchedCases: 1240,
    selectedFixId: "fix-module-1",
    selectedFixTitle: "Point VS Code to the active venv interpreter",
    stepsDone: 3,
    stepsTotal: 3,
    reward: 14,
    rewardStatus: "claimed",
    evidence: ["output", "text"],
    outcome: "resolved",
    verificationConfidence: 97,
    contributor: "Alex Morgan",
    contributorInitials: "AM",
    fixes: [
      {
        id: "fix-module-1",
        rank: 1,
        title: "Point VS Code to the active venv interpreter",
        why: "VS Code defaulted to the global interpreter. Selecting `.venv` makes imports resolve to the same site-packages pip wrote to.",
        successRate: 95,
        matchScore: 97,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "3 minutes",
        steps: [
          "Ctrl+Shift+P → Python: Select Interpreter",
          "Choose `./.venv/Scripts/python.exe`",
          "Re-open the terminal and rerun the script",
        ],
        category: "Coding Error",
        tags: ["python", "venv", "vscode"],
        verifiedCases: 1178,
        isTopPicked: true,
      },
      {
        id: "fix-module-2",
        rank: 2,
        title: "Reinstall with python -m pip",
        why: "Ensures pip targets the interpreter that will run the script, not the system one.",
        successRate: 67,
        matchScore: 52,
        confidence: "Medium",
        risk: "Low",
        effort: "Low",
        estimatedTime: "4 minutes",
        steps: [
          "Activate venv: .venv\\Scripts\\activate",
          "Run python -m pip install requests",
          "Run python app.py from the same activated shell",
        ],
        category: "Coding Error",
        tags: ["python", "pip"],
        verifiedCases: 823,
      },
      {
        id: "fix-module-3",
        rank: 3,
        title: "Add .env with PYTHONPATH pinned to venv",
        why: "Force-resolves imports when an editor ignores the interpreter setting.",
        successRate: 38,
        matchScore: 21,
        confidence: "Low",
        risk: "Medium",
        effort: "Medium",
        estimatedTime: "8 minutes",
        steps: [
          "Create .venv\\Lib\\site-packages path in a .env PYTHONPATH",
          "Restart the editor and the Python language server",
        ],
        category: "Coding Error",
        tags: ["python", "env"],
        verifiedCases: 468,
      },
    ],
    reasoning: [
      { cause: "Editor interpreter differs from shell venv", likelihood: 97 },
      { cause: "pip installed for a different Python version", likelihood: 18 },
      { cause: "Package name mismatch (requests vs beauty requests)", likelihood: 6 },
    ],
    similarCases: [
      { title: "pip install works but import fails in Jupyter", category: "Coding Error", match: 90, outcome: "Verified" },
      { title: "ModuleNotFoundError in VS Code Python 3.11", category: "Coding Error", match: 85, outcome: "Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "ModuleNotFoundError despite pip install", time: "2w ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "1,240 similar cases matched", time: "2w ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Select the venv interpreter", time: "2w ago", tone: "info" },
      { id: "t4", label: "Fix attempted", detail: "Interpreter updated to .venv", time: "2w ago", tone: "violet" },
      { id: "t5", label: "Evidence submitted", detail: "Terminal output before/after", time: "1w ago", tone: "neutral" },
      { id: "t6", label: "Outcome verified", detail: "Imports resolved — +14 FIX earned", time: "1w ago", tone: "success" },
    ],
  },
  {
    id: "case-git",
    title: "Git merge conflict on the main branch",
    category: "Coding Error",
    status: "Verified",
    severity: "High",
    symptom: "Pull request cannot merge — 20+ conflict markers on main.",
    description:
      "Two feature branches both edited `config/env.ts` and `package-lock.json`. Merge attempt produced conflict markers that break the build until resolved.",
    environment: { os: "Windows 11", device: "Laptop", version: "Git 2.44" },
    tags: ["Git", "merge", "conflict"],
    createdAt: "3w ago",
    updatedAt: "2w ago",
    confidence: 92,
    successRate: 90,
    matchedCases: 1580,
    selectedFixId: "fix-git-1",
    selectedFixTitle: "Rebase one branch onto main, then merge",
    stepsDone: 4,
    stepsTotal: 4,
    reward: 9,
    rewardStatus: "claimed",
    evidence: ["code", "output"],
    outcome: "resolved",
    verificationConfidence: 92,
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-git-1",
        rank: 1,
        title: "Rebase one branch onto main, then merge",
        why: "Rebasing replays clean commits on top of main, halving the conflict surface before the merge.",
        successRate: 90,
        matchScore: 91,
        confidence: "High",
        risk: "Medium",
        effort: "High",
        estimatedTime: "15 minutes",
        steps: [
          "git fetch origin && git checkout feature/B",
          "git rebase origin/main",
          "Resolve conflicts in an editor, then git add + git rebase --continue",
          "Merge feature/B into main",
        ],
        category: "Coding Error",
        tags: ["git", "rebase"],
        verifiedCases: 1422,
        isTopPicked: true,
      },
      {
        id: "fix-git-2",
        rank: 2,
        title: "Merge main into feature branch first",
        why: "Safest non-rewriting path; resolves conflicts on the feature branch only.",
        successRate: 77,
        matchScore: 68,
        confidence: "Medium",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "12 minutes",
        steps: [
          "git checkout feature/A",
          "git merge origin/main",
          "Resolve conflicts, commit, push",
        ],
        category: "Coding Error",
        tags: ["git", "merge"],
        verifiedCases: 1204,
      },
      {
        id: "fix-git-3",
        rank: 3,
        title: "Regenerate lockfile after resolving package conflicts",
        why: "Hand-merged package-lock.json edges are a common silent break; regenerate to normalize.",
        successRate: 63,
        matchScore: 41,
        confidence: "Medium",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "6 minutes",
        steps: [
          "After resolving code conflicts, delete package-lock.json",
          "Run npm install to regenerate",
          "Commit the lockfile separately",
        ],
        category: "Coding Error",
        tags: ["git", "npm"],
        verifiedCases: 981,
      },
    ],
    reasoning: [
      { cause: "Divergent edits on shared config + lockfile", likelihood: 91 },
      { cause: "Stale branch based on an old main", likelihood: 47 },
      { cause: "CRLF/LF autocrlf noise in conflicts", likelihood: 12 },
    ],
    similarCases: [
      { title: "Merge conflict on package-lock.json", category: "Coding Error", match: 93, outcome: "Verified" },
      { title: "Conflicts from env.ts shared config", category: "Coding Error", match: 87, outcome: "Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "PR blocked by 20+ conflict markers", time: "3w ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "1,580 similar cases matched", time: "3w ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Rebase one branch onto main", time: "3w ago", tone: "info" },
      { id: "t4", label: "Fix attempted", detail: "Rebase completed, conflicts resolved", time: "2w ago", tone: "violet" },
      { id: "t5", label: "Outcome verified", detail: "PR merged clean — +9 FIX earned", time: "2w ago", tone: "success" },
    ],
  },
  {
    id: "case-docker",
    title: "Docker error: port 5432 is already allocated",
    category: "Coding Error",
    status: "Partially Verified",
    severity: "Medium",
    symptom: "Postgres container fails to start with 'port is already allocated'.",
    description:
      "A second Postgres container cannot bind 5432 because a previous container or local service holds the port. Multiple dev containers rotate ports on every restart.",
    environment: { os: "Windows 11", device: "Dev PC", version: "Docker Desktop 4.29" },
    tags: ["Docker", "ports", "Postgres"],
    createdAt: "1mo ago",
    updatedAt: "4d ago",
    confidence: 90,
    successRate: 84,
    matchedCases: 972,
    selectedFixId: "fix-docker-1",
    selectedFixTitle: "Check binding and remap the host port",
    stepsDone: 3,
    stepsTotal: 3,
    reward: 7,
    rewardStatus: "claimed",
    evidence: ["log"],
    outcome: "partial",
    verificationConfidence: 84,
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-docker-1",
        rank: 1,
        title: "Check binding and remap the host port",
        why: "netstat reveals which PID owns 5432; mapping to 5433 avoids the clash entirely.",
        successRate: 84,
        matchScore: 89,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "4 minutes",
        steps: [
          "netstat -ano | findstr :5432 to find the owning PID",
          "Stop the stale container or local Postgres service",
          "Run the new container with -p 5433:5432",
        ],
        category: "Coding Error",
        tags: ["docker", "ports"],
        verifiedCases: 817,
        isTopPicked: true,
      },
      {
        id: "fix-docker-2",
        rank: 2,
        title: "Remove orphaned docker containers",
        why: "Stopped containers can keep a port reserved after restarts.",
        successRate: 58,
        matchScore: 36,
        confidence: "Medium",
        risk: "Low",
        effort: "Low",
        estimatedTime: "3 minutes",
        steps: [
          "docker ps -a to list all containers",
          "docker rm <id> for the stale Postgres container",
        ],
        category: "Coding Error",
        tags: ["docker", "cleanup"],
        verifiedCases: 561,
      },
      {
        id: "fix-docker-3",
        rank: 3,
        title: "Use explicit port mapping in compose",
        why: "Prevents the driver from reusing a default mapping that another service owns.",
        successRate: 41,
        matchScore: 22,
        confidence: "Low",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "10 minutes",
        steps: [
          "Edit docker-compose.yml ports as 5433:5432",
          "docker compose down && docker compose up -d",
        ],
        category: "Coding Error",
        tags: ["docker", "compose"],
        verifiedCases: 398,
      },
    ],
    reasoning: [
      { cause: "Stale container or local service owns 5432", likelihood: 89 },
      { cause: "Concurrent compose projects racing on defaults", likelihood: 33 },
      { cause: "Windows portproxy / Hyper-V reservation", likelihood: 8 },
    ],
    similarCases: [
      { title: "Docker port 8080 already in use on Windows", category: "Coding Error", match: 91, outcome: "Verified" },
      { title: "Postgres container fails: address in use", category: "Coding Error", match: 84, outcome: "Partially Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "Port 5432 already allocated", time: "1mo ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "972 similar cases matched", time: "1mo ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Remap host port to 5433", time: "1mo ago", tone: "info" },
      { id: "t4", label: "Fix attempted", detail: "Reran on 5433 — connected", time: "4d ago", tone: "violet" },
      { id: "t5", label: "Outcome partially verified", detail: "Needs one more repeat test", time: "4d ago", tone: "warning" },
    ],
  },
  {
    id: "case-printer",
    title: "Printer offline on Windows after driver update",
    category: "Hardware & Devices",
    status: "Needs Verification",
    severity: "Medium",
    symptom: "HP LaserJet shows Offline in Devices and Settings after a driver update.",
    description:
      "A Windows Update refreshed the printer driver; the queue now fails with 'printer offline' even though the USB device is present in Device Manager.",
    environment: { os: "Windows 11", device: "HP LaserJet Pro · USB", version: "23H2", recentChange: "Printer driver updated" },
    tags: ["printer", "HP", "spooler"],
    createdAt: "4d ago",
    updatedAt: "1d ago",
    confidence: 85,
    successRate: 78,
    matchedCases: 913,
    selectedFixId: "fix-printer-1",
    selectedFixTitle: "Restart spooler and re-add printer port",
    stepsDone: 2,
    stepsTotal: 3,
    reward: 6,
    rewardStatus: "pending",
    evidence: ["text"],
    outcome: undefined,
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-printer-1",
        rank: 1,
        title: "Restart spooler and re-add printer port",
        why: "A stuck spooler + stale port is the most common offline cause after driver updates.",
        successRate: 78,
        matchScore: 88,
        confidence: "High",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "8 minutes",
        steps: [
          "Win+R → services.msc → restart 'Print Spooler'",
          "Settings → Bluetooth & devices → Printers",
          "Remove the printer, add it again by name/port",
        ],
        category: "Hardware & Devices",
        tags: ["printer", "spooler"],
        verifiedCases: 712,
        isTopPicked: true,
      },
      {
        id: "fix-printer-2",
        rank: 2,
        title: "Clear corrupt spool files",
        why: "Corrupt .spl files in the spool directory wedge the queue after updates.",
        successRate: 55,
        matchScore: 41,
        confidence: "Medium",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "6 minutes",
        steps: [
          "Stop Spooler, open C:\\Windows\\System32\\spool\\drivers",
          "Delete PRINTERS folder contents, restart Spooler",
        ],
        category: "Hardware & Devices",
        tags: ["printer", "spooler"],
        verifiedCases: 502,
      },
      {
        id: "fix-printer-3",
        rank: 3,
        title: "Roll back the printer driver branch",
        why: "The update bundled a regression for this USB class device; rolling back restores the known-good build.",
        successRate: 36,
        matchScore: 27,
        confidence: "Low",
        risk: "Medium",
        effort: "Medium",
        estimatedTime: "7 minutes",
        steps: [
          "Device Manager → Printer → Driver → Roll Back",
          "Re-add the printer if it disappears",
        ],
        category: "Hardware & Devices",
        tags: ["printer", "driver"],
        verifiedCases: 328,
      },
    ],
    reasoning: [
      { cause: "Spooler wedged after driver update", likelihood: 88 },
      { cause: "USB port profile stale after update reboot", likelihood: 39 },
      { cause: "New driver branch incompatible with device", likelihood: 21 },
    ],
    similarCases: [
      { title: "HP printer offline after Windows Update", category: "Hardware & Devices", match: 90, outcome: "Verified" },
      { title: "Printer queue stuck 'offline' USB", category: "Hardware & Devices", match: 82, outcome: "Partially Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "Printer offline after driver update", time: "4d ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "913 similar cases matched", time: "4d ago", tone: "violet" },
      { id: "t3", label: "Fix attempted", detail: "Spooler restarted, queue cleared", time: "1d ago", tone: "violet" },
      { id: "t4", label: "Awaiting verification", detail: "One more signature needed", time: "1d ago", tone: "warning" },
    ],
  },
  {
    id: "case-node-mem",
    title: "Node.js process exits with 'JavaScript heap out of memory'",
    category: "Performance",
    status: "Verified",
    severity: "Critical",
    symptom: "CI build aborts with heap out of memory after ~2 GB usage.",
    description:
      "A Next.js production build on a 4 GB CI runner exhausts the default Node heap. The failure is intermittent and disappears locally.",
    environment: { os: "Ubuntu 22.04 (CI)", device: "GitHub Actions runner", version: "Node 20" },
    tags: ["Node.js", "heap", "CI"],
    createdAt: "1mo ago",
    updatedAt: "3w ago",
    confidence: 91,
    successRate: 87,
    matchedCases: 1105,
    selectedFixId: "fix-node-1",
    selectedFixTitle: "Raise max-old-space-size in the CI script",
    stepsDone: 2,
    stepsTotal: 2,
    reward: 10,
    rewardStatus: "claimed",
    evidence: ["log"],
    outcome: "resolved",
    verificationConfidence: 91,
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-node-1",
        rank: 1,
        title: "Raise max-old-space-size in the CI script",
        why: "Node's default old-space (~2 GB) is below the runner's limit; NODE_OPTIONS scales the heap to match.",
        successRate: 87,
        matchScore: 92,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "2 minutes",
        steps: [
          "Add NODE_OPTIONS=--max_old_space_size=3072 to the CI env",
          "Rerun the build and confirm heap logs",
        ],
        category: "Performance",
        tags: ["node", "ci", "heap"],
        verifiedCases: 961,
        isTopPicked: true,
      },
      {
        id: "fix-node-2",
        rank: 2,
        title: "Upgrade the runner memory class",
        why: "Some runners throttle heap regardless of flags; a larger runner removes the ceiling.",
        successRate: 52,
        matchScore: 29,
        confidence: "Medium",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "10 minutes",
        steps: [
          "Bump the GitHub Actions runner label (e.g. larger)",
          "Re-run with memory monitoring",
        ],
        category: "Performance",
        tags: ["node", "ci"],
        verifiedCases: 574,
      },
      {
        id: "fix-node-3",
        rank: 3,
        title: "Skip source maps and minimize worker count",
        why: "Reduces peak memory by lowering concurrent processing paths.",
        successRate: 33,
        matchScore: 18,
        confidence: "Low",
        risk: "Medium",
        effort: "Medium",
        estimatedTime: "5 minutes",
        steps: [
          "Set SWC_MINIFY=true and GENERATE_SOURCEMAP=false",
          "Tune NEXT_CPU workers to 1",
        ],
        category: "Performance",
        tags: ["node", "next"],
        verifiedCases: 364,
      },
    ],
    reasoning: [
      { cause: "Default Node heap ceiling hit during parallel build", likelihood: 92 },
      { cause: "Memory-hungry plugin during production compile", likelihood: 27 },
      { cause: "Runner memory throttling", likelihood: 13 },
    ],
    similarCases: [
      { title: "NODE_OPTIONS max-old-space for Vite builds", category: "Performance", match: 88, outcome: "Verified" },
      { title: "CI OOM on Next.js static generation", category: "Performance", match: 84, outcome: "Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "Heap out of memory on CI", time: "1mo ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "1,105 similar cases matched", time: "1mo ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Raise max-old-space-size", time: "1mo ago", tone: "info" },
      { id: "t4", label: "Outcome verified", detail: "CI green across 3 runs — +10 FIX", time: "3w ago", tone: "success" },
    ],
  },
  {
    id: "case-vscode-py",
    title: "VS Code shows no Python interpreter installed",
    category: "Coding Error",
    status: "Verified",
    severity: "Low",
    symptom: "Python extension can't find any interpreter; linting and run buttons are missing.",
    description:
      "The Python extension reports 'No interpreter selected'. A newer VS Code update changed how interpreter discovery resolves the activated environment.",
    environment: { os: "Windows 11", device: "Laptop", version: "VS Code 1.90" },
    tags: ["VS Code", "Python", "interpreter"],
    createdAt: "2mo ago",
    updatedAt: "1mo ago",
    confidence: 89,
    successRate: 86,
    matchedCases: 780,
    selectedFixId: "fix-vscode-1",
    selectedFixTitle: "Rescan and set default interpreter via settings",
    stepsDone: 3,
    stepsTotal: 3,
    reward: 5,
    rewardStatus: "claimed",
    evidence: ["screenshot"],
    outcome: "resolved",
    verificationConfidence: 89,
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-vscode-1",
        rank: 1,
        title: "Rescan and set default interpreter via settings",
        why: "Forcing the interpreter path in settings bypasses broken auto-discovery.",
        successRate: 86,
        matchScore: 90,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "3 minutes",
        steps: [
          "Command Palette → Python: Select Interpreter → Enter path",
          "Set python.defaultInterpreterPath in settings.json",
          "Reload window (Developer: Reload Window)",
        ],
        category: "Coding Error",
        tags: ["vscode", "python"],
        verifiedCases: 671,
        isTopPicked: true,
      },
      {
        id: "fix-vscode-2",
        rank: 2,
        title: "Clear stale python lm interop cache",
        why: "Old cache entries make the extension ignore activated venvs.",
        successRate: 47,
        matchScore: 33,
        confidence: "Medium",
        risk: "Low",
        effort: "Low",
        estimatedTime: "4 minutes",
        steps: [
          "Remove ~/.vscode/lm python discovery cache",
          "Reload the extension host",
        ],
        category: "Coding Error",
        tags: ["vscode", "cache"],
        verifiedCases: 366,
      },
      {
        id: "fix-vscode-3",
        rank: 3,
        title: "Reinstall Python extension",
        why: "A broken extension update is the fallback root cause.",
        successRate: 28,
        matchScore: 15,
        confidence: "Low",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "5 minutes",
        steps: [
          "Uninstall Python extension, reload, reinstall",
        ],
        category: "Coding Error",
        tags: ["vscode"],
        verifiedCases: 218,
      },
    ],
    reasoning: [
      { cause: "Auto-discovery ignored the activated venv", likelihood: 90 },
      { cause: "Stale discovery cache after VS Code update", likelihood: 30 },
      { cause: "Missing Python at system PATH", likelihood: 9 },
    ],
    similarCases: [
      { title: "Python extension broken after VS Code update", category: "Coding Error", match: 88, outcome: "Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "No Python interpreter found", time: "2mo ago", tone: "info" },
      { id: "t2", label: "Fix recommended", detail: "Set default interpreter in settings", time: "2mo ago", tone: "info" },
      { id: "t3", label: "Outcome verified", detail: "Run buttons restored — +5 FIX", time: "1mo ago", tone: "success" },
    ],
  },
  {
    id: "case-chrome",
    title: "Chrome high memory usage with 40+ tabs",
    category: "Performance",
    status: "Partially Verified",
    severity: "Medium",
    symptom: "Chrome consumes 8+ GB RAM; machine slows to a crawl.",
    description:
      "A workstation with 40+ long-lived tabs sees Chrome use 8+ GB. Background extensions and prefetch keep processes alive after tabs are closed.",
    environment: { os: "Windows 11", device: "Workstation", version: "Chrome 126" },
    tags: ["Chrome", "memory", "tabs"],
    createdAt: "1mo ago",
    updatedAt: "1w ago",
    confidence: 87,
    successRate: 80,
    matchedCases: 688,
    selectedFixId: "fix-chrome-1",
    selectedFixTitle: "Memory Saver + trim extensions",
    stepsDone: 4,
    stepsTotal: 4,
    reward: 6,
    rewardStatus: "claimed",
    evidence: ["text"],
    outcome: "partial",
    verificationConfidence: 80,
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-chrome-1",
        rank: 1,
        title: "Memory Saver + trim extensions",
        why: "Chrome's Memory Saver unloads idle tabs; background extensions are the largest controllable leak.",
        successRate: 80,
        matchScore: 86,
        confidence: "High",
        risk: "Low",
        effort: "Low",
        estimatedTime: "5 minutes",
        steps: [
          "chrome://settings/performance → enable Memory Saver",
          "Review chrome://extensions → disable background tabs",
          "Force-quit with chrome://quit to free zombie processes",
        ],
        category: "Performance",
        tags: ["chrome", "memory"],
        verifiedCases: 551,
        isTopPicked: true,
      },
      {
        id: "fix-chrome-2",
        rank: 2,
        title: "Cap sessions to one window + fewer pinned tabs",
        why: "Pinned and sleeping tabs still reserve renderer processes.",
        successRate: 54,
        matchScore: 39,
        confidence: "Medium",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "10 minutes",
        steps: [
          "Close extra windows, keep a single window",
          "Move heavy apps to native/separate browsers",
        ],
        category: "Performance",
        tags: ["chrome", "tabs"],
        verifiedCases: 372,
      },
      {
        id: "fix-chrome-3",
        rank: 3,
        title: "Clear profile bloat and cache",
        why: "A bloated profile directory slows startup and keeps more in memory.",
        successRate: 22,
        matchScore: 11,
        confidence: "Low",
        risk: "Medium",
        effort: "Medium",
        estimatedTime: "8 minutes",
        steps: [
          "chrome://settings/clear-browser-data → cached images",
          "De-authorize unused profiles",
        ],
        category: "Performance",
        tags: ["chrome", "cache"],
        verifiedCases: 151,
      },
    ],
    reasoning: [
      { cause: "Background extensions + prefetch holding processes", likelihood: 86 },
      { cause: "40+ pinned tabs keeping renderers alive", likelihood: 44 },
      { cause: "Memory leak in a specific extension version", likelihood: 12 },
    ],
    similarCases: [
      { title: "Chrome 8GB RAM with many tabs", category: "Performance", match: 90, outcome: "Verified" },
      { title: "Chrome background processes after close", category: "Performance", match: 83, outcome: "Partially Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "8+ GB Chrome usage", time: "1mo ago", tone: "info" },
      { id: "t2", label: "Fix recommended", detail: "Memory Saver + trim extensions", time: "1mo ago", tone: "info" },
      { id: "t3", label: "Outcome partially verified", detail: "Usage down 60%; one more test", time: "1w ago", tone: "warning" },
    ],
  },
  {
    id: "case-supabase",
    title: "Supabase auth session expiring after page refresh",
    category: "Coding Error",
    status: "Needs Verification",
    severity: "High",
    symptom: "User gets signed out after any hard refresh on the client app.",
    description:
      "Next.js app uses supabase-js with cookie storage. Sessions work in-memory but are lost on refresh — storage type and server auth config mismatch.",
    environment: { os: "Windows 11", device: "Dev PC", version: "supabase-js v2" },
    tags: ["Supabase", "auth", "cookies"],
    createdAt: "3d ago",
    updatedAt: "3d ago",
    confidence: 90,
    successRate: 83,
    matchedCases: 934,
    selectedFixId: null,
    stepsDone: 0,
    stepsTotal: 4,
    reward: 8,
    rewardStatus: "none",
    evidence: ["code"],
    outcome: undefined,
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-supabase-1",
        rank: 1,
        title: "Persist session with refresh tokens in cookies",
        why: "supabase-js default localStorage won't survive SSR/refresh; cookie persistence with automatic refresh keeps the session alive.",
        successRate: 83,
        matchScore: 91,
        confidence: "High",
        risk: "Low",
        effort: "High",
        estimatedTime: "20 minutes",
        steps: [
          "Set storage: createClient(..., { cookies })",
          "Exchange codes server-side or with PKCE",
          "Refresh the session on every route via middleware",
        ],
        category: "Coding Error",
        tags: ["supabase", "auth", "ssr"],
        verifiedCases: 776,
        isTopPicked: true,
      },
      {
        id: "fix-supabase-2",
        rank: 2,
        title: "Enable persistent sessions on the Supabase dashboard",
        why: "Some projects disable persistent sessions, dropping cookies immediately.",
        successRate: 48,
        matchScore: 34,
        confidence: "Medium",
        risk: "Low",
        effort: "Low",
        estimatedTime: "5 minutes",
        steps: [
          "Dashboard → Auth → URLs",
          "Turn on 'Persistent sessions' and set session duration",
        ],
        category: "Coding Error",
        tags: ["supabase", "auth"],
        verifiedCases: 463,
      },
      {
        id: "fix-supabase-3",
        rank: 3,
        title: "Align auth callback URL with production host",
        why: "A host mismatch invalidates cookies across refreshes on deployed domains.",
        successRate: 29,
        matchScore: 16,
        confidence: "Low",
        risk: "Medium",
        effort: "Medium",
        estimatedTime: "8 minutes",
        steps: [
          "Update Auth → URL configuration to the production origin",
          "Test login → refresh on the deployed URL",
        ],
        category: "Coding Error",
        tags: ["supabase", "auth"],
        verifiedCases: 281,
      },
    ],
    reasoning: [
      { cause: "Session stored in non-persistent memory storage", likelihood: 91 },
      { cause: "Missing server-side auth session creation", likelihood: 40 },
      { cause: "Auth callback host mismatch in dashboard", likelihood: 12 },
    ],
    similarCases: [
      { title: "Supabase session lost on refresh Next.js", category: "Coding Error", match: 93, outcome: "Verified" },
      { title: "Auth refresh token rotation failing on deploy", category: "Coding Error", match: 79, outcome: "Partially Verified" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "Logged out on hard refresh", time: "3d ago", tone: "info" },
      { id: "t2", label: "AI analysis complete", detail: "934 similar cases matched", time: "3d ago", tone: "violet" },
      { id: "t3", label: "Fix recommended", detail: "Cookie persistence + refresh tokens", time: "3d ago", tone: "info" },
    ],
  },
  {
    id: "case-next-build",
    title: "Next.js production build fails on CI with TypeScript errors",
    category: "Coding Error",
    status: "Failed",
    severity: "Critical",
    symptom: "next build exits with type errors only on the CI machine.",
    description:
      "Build passes locally but fails on CI with missing type declarations. A generated contract file is gitignored, so fresh checkouts lack the type.",
    environment: { os: "Ubuntu 22.04 (CI)", device: "GitHub Actions runner", version: "Next.js 15" },
    tags: ["Next.js", "CI", "typescript"],
    createdAt: "2mo ago",
    updatedAt: "6w ago",
    confidence: 84,
    successRate: 60,
    matchedCases: 512,
    selectedFixId: "fix-next-1",
    selectedFixTitle: "Commit the generated types + pre-build codegen",
    stepsDone: 1,
    stepsTotal: 2,
    reward: 0,
    rewardStatus: "none",
    evidence: ["log"],
    outcome: "not-resolved",
    contributor: "Community",
    contributorInitials: "CM",
    fixes: [
      {
        id: "fix-next-1",
        rank: 1,
        title: "Commit the generated types + pre-build codegen",
        why: "Gitignored generated types are missing on fresh checkouts, which breaks typecheck in CI.",
        successRate: 60,
        matchScore: 87,
        confidence: "High",
        risk: "Low",
        effort: "Medium",
        estimatedTime: "10 minutes",
        steps: [
          "Run the codegen step before next build in CI",
          "Commit .d.ts output for generated contracts",
        ],
        category: "Coding Error",
        tags: ["next", "ci", "ts"],
        verifiedCases: 312,
        isTopPicked: true,
      },
      {
        id: "fix-next-2",
        rank: 2,
        title: "Skip typecheck during build, gate on lint job",
        why: "Moves typecheck to a dedicated step with a clearer error surface.",
        successRate: 41,
        matchScore: 33,
        confidence: "Medium",
        risk: "Medium",
        effort: "Low",
        estimatedTime: "5 minutes",
        steps: [
          "Set typescript.ignoreBuildErrors=true",
          "Add a separate typecheck step in CI",
        ],
        category: "Coding Error",
        tags: ["next", "ci"],
        verifiedCases: 348,
      },
      {
        id: "fix-next-3",
        rank: 3,
        title: "Freeze Node/Next versions on the runner",
        why: "Version drift between local and CI reproduces intermittent type behavior.",
        successRate: 22,
        matchScore: 12,
        confidence: "Low",
        risk: "Low",
        effort: "Low",
        estimatedTime: "3 minutes",
        steps: [
          "Pin engines + action versions in CI workflow",
        ],
        category: "Coding Error",
        tags: ["next", "ci"],
        verifiedCases: 194,
      },
    ],
    reasoning: [
      { cause: "Missing generated types on fresh checkout", likelihood: 87 },
      { cause: "Node/Next version drift on runner", likelihood: 18 },
      { cause: "Memory-limited typecheck flake", likelihood: 6 },
    ],
    similarCases: [
      { title: "CI-only TS build failures from ignored types", category: "Coding Error", match: 91, outcome: "Verified" },
      { title: "next build fails only on GitHub Actions", category: "Coding Error", match: 85, outcome: "Failed" },
    ],
    timeline: [
      { id: "t1", label: "Problem submitted", detail: "TS errors on CI only", time: "2mo ago", tone: "info" },
      { id: "t2", label: "Fix attempted", detail: "Committed generated types", time: "7w ago", tone: "violet" },
      { id: "t3", label: "Outcome not resolved", detail: "CI still failing on a second module", time: "6w ago", tone: "danger" },
    ],
  },
];

// ---- Hydration analysis, reused by the interactive demo AND the diagnosis service ----
export const hydrationAnalysis: AnalysisResult = {
  summary:
    "The React app produces different output on the server and the client for the same component. Because the header renders a live clock value, the server HTML contains one time and the client renders another during hydration — React aborts the hydration and logs a mismatch warning, then re-renders the tree on the client.",
  likelyCause: "Client-only timestamp rendered during SSR causes a hydration mismatch.",
  confidence: 96,
  matchedCases: 487,
  reasoning: [
    { cause: "Timestamp from the client clock renders on both sides differently", likelihood: 96 },
    { cause: "Locale/timezone difference between server and client", likelihood: 6 },
    { cause: "Browser extension mutating the DOM before hydration", likelihood: 3 },
  ],
  fixes: [
    {
      id: "fix-hydration-1",
      rank: 1,
      title: "Render timestamps client-side only",
      why: "Dates from the client clock never match server HTML. Mount the value inside useEffect so SSR renders a stable placeholder and the client fills it in after mount.",
      successRate: 91,
      matchScore: 93,
      confidence: "High",
      risk: "Low",
      effort: "Low",
      estimatedTime: "5 minutes",
      steps: [
        "Extract the clock into a client component",
        "Render a stable placeholder during SSR",
        "Set the real time inside useEffect after mount",
      ],
      category: "Coding Error",
      tags: ["react", "hydration", "ssr"],
      verifiedCases: 443,
      isTopPicked: true,
    },
    {
      id: "fix-hydration-2",
      rank: 2,
      title: "Use suppressHydrationWarning on the leaf node",
      why: "Silences the warning only when the mismatch is intentional and harmless — applied to the exact leaf element containing the time.",
      successRate: 58,
      matchScore: 44,
      confidence: "Medium",
      risk: "Low",
      effort: "Low",
      estimatedTime: "2 minutes",
      steps: [
        "Locate the exact element rendering the time",
        "Add suppressHydrationWarning to that element only",
      ],
      category: "Coding Error",
      tags: ["react", "hydration"],
      verifiedCases: 282,
    },
    {
      id: "fix-hydration-3",
      rank: 3,
      title: "Derive the time from a stable SSR context",
      why: "Serve an identical timestamp on both sides via a server-computed value so the output matches exactly.",
      successRate: 41,
      matchScore: 28,
      confidence: "Low",
      risk: "Medium",
      effort: "Medium",
      estimatedTime: "15 minutes",
      steps: [
        "Compute the time once on the server",
        "Pass it through props/context to the client",
      ],
      category: "Coding Error",
      tags: ["react", "ssr"],
      verifiedCases: 199,
    },
  ],
  similarCases: [
    { title: "Hydration mismatch on date-fns formatted dates", category: "Coding Error", match: 92, outcome: "Verified" },
    { title: "Clock flicker in dashboard header (Next.js)", category: "Coding Error", match: 88, outcome: "Verified" },
    { title: "Text mismatch after SSR + client mount", category: "Coding Error", match: 81, outcome: "Partially Verified" },
  ],
};

// ---- Wi-Fi analysis, reused by the interactive demo and the diagnosis service ----
export const wifiAnalysis: AnalysisResult = {
  summary:
    "The laptop drops its Wi-Fi connection roughly every 10–15 minutes since the last Windows update. Other devices on the same network stay connected, which narrows the fault to the client adapter, its driver, or power-management policies rather than the router itself.",
  likelyCause: "Intel Wi-Fi driver regression introduced by the recent Windows update.",
  confidence: 94,
  matchedCases: 1842,
  reasoning: [
    { cause: "Intel Wi-Fi driver regression introduced by the update", likelihood: 94 },
    { cause: "Adapter power management trimming radio power", likelihood: 41 },
    { cause: "IPv6 + DHCP lease churn on the adapter", likelihood: 18 },
  ],
  fixes: [
    {
      id: "fix-wifi-1",
      rank: 1,
      title: "Rollback Intel Wi-Fi Driver",
      why: "The update pulled a regression for the Wi-Fi adapter family. Rolling back to the previous Intel driver removes the adapter reset signature.",
      successRate: 82,
      matchScore: 94,
      confidence: "High",
      risk: "Low",
      effort: "Low",
      estimatedTime: "5 minutes",
      steps: [
        "Open Device Manager → Network adapters → Intel Wi-Fi",
        "Properties → Driver → Roll Back Driver",
        "Reboot and reconnect to the network",
        "Observe connection stability for 10 minutes",
      ],
      category: "Network & Wi-Fi",
      tags: ["driver", "rollback", "intel"],
      verifiedCases: 1511,
      isTopPicked: true,
    },
    {
      id: "fix-wifi-2",
      rank: 2,
      title: "Network Adapter Reset",
      why: "Clears corrupted adapter state carried over from the update. Lower success but zero risk.",
      successRate: 47,
      matchScore: 71,
      confidence: "Medium",
      risk: "Low",
      effort: "Low",
      estimatedTime: "4 minutes",
      steps: [
        "Settings → Network & Internet → Advanced network settings",
        "Network reset → Reset now",
        "Reconnect and re-enter the Wi-Fi password",
      ],
      category: "Network & Wi-Fi",
      tags: ["network", "reset"],
      verifiedCases: 866,
    },
    {
      id: "fix-wifi-3",
      rank: 3,
      title: "DNS Configuration Change",
      why: "Rare fit but cheap to try when the driver path has been exhausted.",
      successRate: 12,
      matchScore: 22,
      confidence: "Low",
      risk: "Medium",
      effort: "Medium",
      estimatedTime: "6 minutes",
      steps: [
        "Open adapter properties → IPv4 → Properties",
        "Set DNS to 1.1.1.1 and 1.0.0.1",
        "Flush DNS: ipconfig /flushdns",
      ],
      category: "Network & Wi-Fi",
      tags: ["dns"],
      verifiedCases: 221,
    },
  ],
  similarCases: [
    { title: "Intel AX210 disconnects after cumulative update", category: "Network & Wi-Fi", match: 96, outcome: "Verified" },
    { title: "AX211 adapter resets during Teams calls", category: "Network & Wi-Fi", match: 89, outcome: "Verified" },
    { title: "Windows 11 drops Wi-Fi ~15 min after reboot", category: "Network & Wi-Fi", match: 83, outcome: "Partially Verified" },
  ],
};

export function findAnalysisFor(input: {
  title: string;
  description: string;
  category: string;
}): AnalysisResult {
  const text = `${input.title} ${input.description}`.toLowerCase();
  if (text.includes("hydrat") || text.includes("next.js") || text.includes("react")) {
    return hydrationAnalysis;
  }
  if (
    text.includes("wifi") ||
    text.includes("wi-fi") ||
    text.includes("network") ||
    text.includes("adapter") ||
    text.includes("internet")
  ) {
    return wifiAnalysis;
  }
  if (text.includes("python") || text.includes("module")) {
    return pythonAnalysis;
  }
  if (text.includes("excel") || text.includes("xlookup")) {
    return xlookupAnalysis;
  }
  if (text.includes("docker") || text.includes("port")) {
    return dockerAnalysis;
  }
  return hydrationAnalysis;
}

const pythonAnalysis: AnalysisResult = {
  summary:
    "The script raises ModuleNotFoundError even though the package install reported success. The most common cause is that the environment running the script differs from the environment where pip installed the package.",
  likelyCause: "Editor/shell interpreter mismatch with the active virtual environment.",
  confidence: 97,
  matchedCases: 1240,
  reasoning: [
    { cause: "Editor interpreter differs from shell venv", likelihood: 97 },
    { cause: "pip installed for a different Python version", likelihood: 18 },
    { cause: "Package name mismatch", likelihood: 6 },
  ],
  fixes: [
    {
      id: "fix-module-1",
      rank: 1,
      title: "Point VS Code to the active venv interpreter",
      why: "VS Code defaults to the global interpreter. Selecting the venv makes imports resolve to the same site-packages pip wrote to.",
      successRate: 95,
      matchScore: 97,
      confidence: "High",
      risk: "Low",
      effort: "Low",
      estimatedTime: "3 minutes",
      steps: [
        "Ctrl+Shift+P → Python: Select Interpreter",
        "Choose .venv/Scripts/python.exe",
        "Re-open the terminal and rerun the script",
      ],
      category: "Coding Error",
      tags: ["python", "venv", "vscode"],
      verifiedCases: 1178,
      isTopPicked: true,
    },
    {
      id: "fix-module-2",
      rank: 2,
      title: "Reinstall with python -m pip",
      why: "Ensures pip targets the interpreter that will run the script.",
      successRate: 67,
      matchScore: 52,
      confidence: "Medium",
      risk: "Low",
      effort: "Low",
      estimatedTime: "4 minutes",
      steps: [
        "Activate venv: .venv\\Scripts\\activate",
        "Run python -m pip install <package>",
        "Run python app.py from the same activated shell",
      ],
      category: "Coding Error",
      tags: ["python", "pip"],
      verifiedCases: 823,
    },
  ],
  similarCases: [
    { title: "pip install works but import fails in Jupyter", category: "Coding Error", match: 90, outcome: "Verified" },
    { title: "ModuleNotFoundError in VS Code Python 3.11", category: "Coding Error", match: 85, outcome: "Verified" },
  ],
};

const xlookupAnalysis: AnalysisResult = {
  summary:
    "XLOOKUP returns #N/A even though the lookup value exists. The function requires lookup_vector and return_array to start on the same row; an offset anchor silently breaks the match.",
  likelyCause: "lookup_vector and return_array ranges are offset.",
  confidence: 88,
  matchedCases: 612,
  reasoning: [
    { cause: "lookup_vector and return_array ranges are offset", likelihood: 86 },
    { cause: "Text contains invisible whitespace or mismatched types", likelihood: 39 },
    { cause: "search_mode incompatible with unsorted data", likelihood: 11 },
  ],
  fixes: [
    {
      id: "fix-xlookup-1",
      rank: 1,
      title: "Match lookup_vector and return_array spans",
      why: "XLOOKUP requires both ranges to start on the same row. A one-row offset returns #N/A for everything.",
      successRate: 74,
      matchScore: 86,
      confidence: "High",
      risk: "Low",
      effort: "Low",
      estimatedTime: "3 minutes",
      steps: [
        "Confirm lookup_vector and return_array start on the same row",
        "Rewrite ranges with identical anchors",
        "Re-test with a static lookup value",
      ],
      category: "Apps & Productivity",
      tags: ["excel", "xlookup"],
      verifiedCases: 452,
      isTopPicked: true,
    },
    {
      id: "fix-xlookup-2",
      rank: 2,
      title: "Strip invisible whitespace and coerce types",
      why: "Trailing spaces or text-vs-number types make exact matches fail silently.",
      successRate: 51,
      matchScore: 39,
      confidence: "Medium",
      risk: "Low",
      effort: "Medium",
      estimatedTime: "8 minutes",
      steps: [
        "Apply TRIM to the lookup and search ranges",
        "Use VALUE/NUMBERVALUE to normalize numeric cells",
      ],
      category: "Apps & Productivity",
      tags: ["excel", "trim"],
      verifiedCases: 311,
    },
  ],
  similarCases: [
    { title: "XLOOKUP #N/A after hiding helper column", category: "Apps & Productivity", match: 82, outcome: "Verified" },
    { title: "VLOOKUP vs XLOOKUP range anchor drift", category: "Apps & Productivity", match: 76, outcome: "Partially Verified" },
  ],
};

const dockerAnalysis: AnalysisResult = {
  summary:
    "A container cannot start because the host port is already allocated. Either a previous container still owns the port or a local service bound it before Docker started.",
  likelyCause: "Host port 5432 is held by a stale container or local service.",
  confidence: 90,
  matchedCases: 972,
  reasoning: [
    { cause: "Stale container or local service owns the port", likelihood: 89 },
    { cause: "Concurrent compose projects racing on defaults", likelihood: 33 },
    { cause: "Windows portproxy / Hyper-V reservation", likelihood: 8 },
  ],
  fixes: [
    {
      id: "fix-docker-1",
      rank: 1,
      title: "Check binding and remap the host port",
      why: "netstat reveals which PID owns the port; remapping avoids the clash entirely.",
      successRate: 84,
      matchScore: 89,
      confidence: "High",
      risk: "Low",
      effort: "Low",
      estimatedTime: "4 minutes",
      steps: [
        "netstat -ano | findstr :5432",
        "Stop the stale container or local service",
        "Run the container with -p 5433:5432",
      ],
      category: "Coding Error",
      tags: ["docker", "ports"],
      verifiedCases: 817,
      isTopPicked: true,
    },
    {
      id: "fix-docker-2",
      rank: 2,
      title: "Remove orphaned docker containers",
      why: "Stopped containers can keep a port reserved after restarts.",
      successRate: 58,
      matchScore: 36,
      confidence: "Medium",
      risk: "Low",
      effort: "Low",
      estimatedTime: "3 minutes",
      steps: [
        "docker ps -a to list all containers",
        "docker rm <id> for stale containers",
      ],
      category: "Coding Error",
      tags: ["docker", "cleanup"],
      verifiedCases: 561,
    },
  ],
  similarCases: [
    { title: "Docker port 8080 already in use on Windows", category: "Coding Error", match: 91, outcome: "Verified" },
    { title: "Postgres container fails: address in use", category: "Coding Error", match: 84, outcome: "Partially Verified" },
  ],
};