import type { Contribution, ContributionTask } from "./types";

export const contributions: Contribution[] = [
  {
    id: "con-hydration",
    caseId: "case-hydration",
    title: "React hydration mismatch caused by client-only timestamp",
    category: "Coding Error",
    fix: "Render timestamps client-side only (useEffect + stable placeholder)",
    reward: 8,
    royalty: 6.4,
    reuseCount: 14,
    verifiedAt: "4d ago",
    outcome: "Verified",
    status: "Verified",
  },
  {
    id: "con-wifi",
    caseId: "case-wifi",
    title: "Intel Wi-Fi driver rollback after Windows update",
    category: "Network & Wi-Fi",
    fix: "Roll back the Intel driver to the pre-update build",
    reward: 120,
    royalty: 11.4,
    reuseCount: 23,
    verifiedAt: "2w ago",
    outcome: "Verified",
    status: "Verified",
  },
  {
    id: "con-module",
    caseId: "case-module",
    title: "Python ModuleNotFoundError after pip install",
    category: "Coding Error",
    fix: "Point the editor at the active venv interpreter",
    reward: 14,
    royalty: 2.2,
    reuseCount: 11,
    verifiedAt: "1w ago",
    outcome: "Verified",
    status: "Verified",
  },
  {
    id: "con-xlookup",
    caseId: "case-xlookup",
    title: "Excel XLOOKUP returning #N/A for existing values",
    category: "Apps & Productivity",
    fix: "Align lookup_vector and return_array ranges",
    reward: 10,
    royalty: 0,
    reuseCount: 0,
    verifiedAt: "12h ago",
    outcome: "Needs Verification",
    status: "Pending Review",
  },
  {
    id: "con-bluetooth",
    caseId: "case-bluetooth",
    title: "Bluetooth driver failure on Windows 11",
    category: "Hardware & Devices",
    fix: "Reset BT radio stack + re-pair device",
    reward: 7,
    royalty: 0,
    reuseCount: 2,
    verifiedAt: "2d ago",
    outcome: "Needs Verification",
    status: "Pending Review",
  },
];

export const contributionTasks: ContributionTask[] = [
  {
    id: "task-hydration",
    type: "verify",
    title: "React Hydration Error",
    category: "Coding Error",
    difficulty: "Moderate",
    rewardMin: 4,
    rewardMax: 8,
    stake: 0,
    confidenceNeeded: 85,
    urgency: "High",
    casesAwaiting: 182,
    description: "Confirm the client-only timestamp fix against 3 fresh hydration warnings and attach build output as proof.",
    verificationNeeded: "Code / Test",
  },
  {
    id: "task-bluetooth",
    type: "fix",
    title: "Windows Bluetooth Driver Failure",
    category: "Hardware & Devices",
    difficulty: "Easy",
    rewardMin: 3,
    rewardMax: 7,
    stake: 2,
    confidenceNeeded: 80,
    urgency: "Medium",
    casesAwaiting: 96,
    description: "A working BT driver reset + re-pair runbook for Windows 11, with step evidence from a real device.",
    verificationNeeded: "Log / Test",
  },
  {
    id: "task-docker",
    type: "fix",
    title: "Docker Port Already Allocated",
    category: "Coding Error",
    difficulty: "Moderate",
    rewardMin: 5,
    rewardMax: 10,
    stake: 4,
    confidenceNeeded: 88,
    urgency: "Medium",
    casesAwaiting: 141,
    description: "Solid, reproducible steps to release an occupied host port and remap containers safely.",
    verificationNeeded: "Log / Output",
  },
  {
    id: "task-excel",
    type: "improve",
    title: "Excel XLOOKUP #N/A workaround",
    category: "Apps & Productivity",
    difficulty: "Easy",
    rewardMin: 3,
    rewardMax: 6,
    stake: 0,
    confidenceNeeded: 82,
    urgency: "Low",
    casesAwaiting: 64,
    description: "Strengthen the existing range-alignment write-up with a before/after workbook example.",
    verificationNeeded: "Output",
  },
  {
    id: "task-supabase",
    type: "verify",
    title: "Supabase Auth Session Expiring",
    category: "Coding Error",
    difficulty: "Expert",
    rewardMin: 6,
    rewardMax: 12,
    stake: 5,
    confidenceNeeded: 90,
    urgency: "High",
    casesAwaiting: 210,
    description: "Validate cookie persistence + refresh-token rotation across a hard refresh on Next.js.",
    verificationNeeded: "Code / Test",
  },
  {
    id: "task-printer",
    type: "fix",
    title: "Printer Offline on Windows",
    category: "Hardware & Devices",
    difficulty: "Easy",
    rewardMin: 4,
    rewardMax: 8,
    stake: 0,
    confidenceNeeded: 80,
    urgency: "Low",
    casesAwaiting: 57,
    description: "A spooler reset + re-add port runbook verified on at least two printer models.",
    verificationNeeded: "Output",
  },
];