import type { LeaderboardEntry } from "./types";

export const leaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    name: "Maya Chen",
    handle: "@mayabuilds",
    initials: "MC",
    title: "Expert Solver",
    reputation: 12450,
    verified: 482,
    successRate: 97,
    impact: "12,480 cases helped",
    fixEarned: 4290,
    movement: 0,
    streak: 84,
    badge: "Verification Master",
  },
  {
    rank: 2,
    name: "Daniel Kim",
    handle: "@danielkim",
    initials: "DK",
    title: "Expert Solver",
    reputation: 11020,
    verified: 431,
    successRate: 95,
    impact: "10,210 cases helped",
    fixEarned: 3810,
    movement: 1,
    streak: 61,
    badge: "Fix Architect",
  },
  {
    rank: 3,
    name: "Sofia Rossi",
    handle: "@sofiarossi",
    initials: "SR",
    title: "Solver",
    reputation: 9820,
    verified: 389,
    successRate: 93,
    impact: "8,940 cases helped",
    fixEarned: 3340,
    movement: -1,
    streak: 47,
    badge: "Top Diagnostician",
  },
  {
    rank: 4,
    name: "Ayesha Raza",
    handle: "@ayeshafixes",
    initials: "AR",
    title: "Expert Solver",
    reputation: 9210,
    verified: 371,
    successRate: 94,
    impact: "8,120 cases helped",
    fixEarned: 3050,
    movement: 0,
    streak: 52,
    badge: "Crowd Verifier",
  },
  {
    rank: 5,
    name: "Daniel Osei",
    handle: "@danielcodes",
    initials: "DO",
    title: "Solver",
    reputation: 8640,
    verified: 344,
    successRate: 92,
    impact: "7,310 cases helped",
    fixEarned: 2720,
    movement: 2,
    streak: 34,
  },
  {
    rank: 6,
    name: "Nadia Karim",
    handle: "@nadiafix",
    initials: "NK",
    title: "Solver",
    reputation: 7930,
    verified: 312,
    successRate: 93,
    impact: "6,540 cases helped",
    fixEarned: 2410,
    movement: 0,
    streak: 29,
  },
  {
    rank: 7,
    name: "Oliver Grant",
    handle: "@oliverops",
    initials: "OG",
    title: "Solver",
    reputation: 7240,
    verified: 289,
    successRate: 88,
    impact: "5,880 cases helped",
    fixEarned: 2180,
    movement: -2,
    streak: 18,
  },
  {
    rank: 8,
    name: "Sara Malik",
    handle: "@saramlks",
    initials: "SM",
    title: "Solver",
    reputation: 6610,
    verified: 264,
    successRate: 90,
    impact: "5,120 cases helped",
    fixEarned: 1900,
    movement: 0,
    streak: 22,
  },
  {
    rank: 9,
    name: "Tomás Herrera",
    handle: "@tomasdev",
    initials: "TH",
    title: "Contributor",
    reputation: 5970,
    verified: 241,
    successRate: 89,
    impact: "4,460 cases helped",
    fixEarned: 1720,
    movement: 3,
    streak: 14,
  },
  {
    rank: 10,
    name: "Jonas Weber",
    handle: "@jonasmake",
    initials: "JW",
    title: "Contributor",
    reputation: 5480,
    verified: 220,
    successRate: 86,
    impact: "3,990 cases helped",
    fixEarned: 1540,
    movement: 0,
    streak: 9,
  },
  {
    rank: 11,
    name: "Fatima Noor",
    handle: "@fatimadbg",
    initials: "FN",
    title: "Contributor",
    reputation: 5120,
    verified: 205,
    successRate: 88,
    impact: "3,610 cases helped",
    fixEarned: 1390,
    movement: -1,
    streak: 11,
  },
  {
    rank: 12,
    name: "Priya Nair",
    handle: "@priyafixes",
    initials: "PN",
    title: "Contributor",
    reputation: 4880,
    verified: 194,
    successRate: 87,
    impact: "3,320 cases helped",
    fixEarned: 1260,
    movement: 0,
    streak: 7,
  },
  {
    rank: 13,
    name: "Rania Aziz",
    handle: "@raniafix",
    initials: "RA",
    title: "Contributor",
    reputation: 4730,
    verified: 188,
    successRate: 86,
    impact: "3,050 cases helped",
    fixEarned: 1140,
    movement: 1,
    streak: 6,
  },
  {
    rank: 14,
    name: "M. Bilal",
    handle: "@mbilal",
    initials: "MB",
    title: "Contributor",
    reputation: 4650,
    verified: 182,
    successRate: 89,
    impact: "2,910 cases helped",
    fixEarned: 1080,
    movement: 0,
    streak: 5,
  },
  {
    rank: 15,
    name: "Hana Suzuki",
    handle: "@hanacodes",
    initials: "HS",
    title: "Contributor",
    reputation: 4970,
    verified: 176,
    successRate: 91,
    impact: "2,760 cases helped",
    fixEarned: 1010,
    movement: 2,
    streak: 8,
  },
  {
    rank: 16,
    name: "Leo Fischer",
    handle: "@leofix",
    initials: "LF",
    title: "Contributor",
    reputation: 5030,
    verified: 171,
    successRate: 88,
    impact: "2,540 cases helped",
    fixEarned: 960,
    movement: -1,
    streak: 4,
  },
  {
    rank: 17,
    name: "Isabel Moreau",
    handle: "@isabelmore",
    initials: "IM",
    title: "Contributor",
    reputation: 4890,
    verified: 166,
    successRate: 90,
    impact: "2,330 cases helped",
    fixEarned: 910,
    movement: 0,
    streak: 6,
  },
  {
    rank: 18,
    name: "Alex Morgan",
    handle: "@alexmorgan",
    initials: "AM",
    title: "Expert Solver",
    reputation: 4820,
    verified: 42,
    successRate: 91,
    impact: "37 cases helped this week",
    fixEarned: 284,
    movement: 3,
    streak: 12,
    isYou: true,
  },
  {
    rank: 19,
    name: "Yunseo Park",
    handle: "@yunseo",
    initials: "YP",
    title: "Contributor",
    reputation: 4710,
    verified: 158,
    successRate: 87,
    impact: "2,120 cases helped",
    fixEarned: 860,
    movement: 1,
    streak: 3,
  },
  {
    rank: 20,
    name: "Ravi Patel",
    handle: "@ravifixes",
    initials: "RP",
    title: "Contributor",
    reputation: 4620,
    verified: 152,
    successRate: 85,
    impact: "1,980 cases helped",
    fixEarned: 820,
    movement: 0,
    streak: 2,
  },
];

export const leaderboardPools = {
  weekly: 1250,
  monthly: 4200,
  allTime: 18000,
};