import type { NotificationItem } from "./types";

export const notifications: NotificationItem[] = [
  {
    id: "n-1",
    title: "+8 FIX reward unlocked",
    body: "Your React hydration fix passed outcome verification.",
    time: "2h ago",
    kind: "reward",
    unread: true,
    actionHref: "/rewards",
  },
  {
    id: "n-2",
    title: "Outcome verification complete",
    body: "Wi-Fi case entered an 18h observation window — final check after 24h.",
    time: "3h ago",
    kind: "case",
    unread: true,
    actionHref: "/cases/case-wifi",
  },
  {
    id: "n-3",
    title: "Someone benefited from your fix",
    body: "Your hydration fix was used in 14 premium diagnoses this week.",
    time: "5h ago",
    kind: "reward",
    unread: true,
    actionHref: "/profile",
  },
  {
    id: "n-4",
    title: "2.4 FIX royalty earned",
    body: "New royalty accrued for reusing your timestamp fix.",
    time: "1d ago",
    kind: "reward",
    unread: true,
    actionHref: "/rewards",
  },
  {
    id: "n-5",
    title: "New case matches your expertise",
    body: "Supabase auth session expiring on refresh — React + auth.",
    time: "1d ago",
    kind: "case",
    unread: true,
    actionHref: "/contribute",
  },
  {
    id: "n-6",
    title: "Leaderboard rank increased",
    body: "You moved up to #18 this week. Keep contributing!",
    time: "2d ago",
    kind: "system",
    unread: false,
    actionHref: "/leaderboard",
  },
  {
    id: "n-7",
    title: "Stake yield accrued · 1.2 FIX",
    body: "Your 20 FIX confidence stake earned yield this month.",
    time: "3d ago",
    kind: "system",
    unread: false,
    actionHref: "/rewards",
  },
  {
    id: "n-8",
    title: "Fix verified · Python venv",
    body: "Your interpreter-mismatch fix was verified by the community.",
    time: "1w ago",
    kind: "reward",
    unread: false,
    actionHref: "/cases/case-module",
  },
  {
    id: "n-9",
    title: "Contribution pending review",
    body: "Your Excel XLOOKUP write-up needs one more evidence signature.",
    time: "1w ago",
    kind: "case",
    unread: false,
    actionHref: "/contribute",
  },
  {
    id: "n-10",
    title: "Welcome to FixMind",
    body: "Finish your profile and take the 1-minute product tour.",
    time: "1mo ago",
    kind: "system",
    unread: false,
    actionHref: "/settings",
  },
];