"""Phase 3 application schema"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '76d47059c7bc'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('auth_user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('reputation_level', sa.String(length=255), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('auth_user_id', name=op.f('uq_profiles_auth_user_id')),
    sa.UniqueConstraint('username', name=op.f('uq_profiles_username'))
    )
    op.create_table('account_deletion_requests',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_account_deletion_requests_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_deletion_requests')),
    sa.UniqueConstraint('user_id', name=op.f('uq_account_deletion_requests_user_id'))
    )
    op.create_table('audit_events',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_audit_events_user_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('cases',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('software_name', sa.String(length=255), nullable=True),
    sa.Column('software_version', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('recent_changes', sa.Text(), nullable=True),
    sa.Column('current_diagnosis_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_cases_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('id', 'user_id', name=op.f('uq_cases_id'))
    )
    op.create_index('ix_cases_user_created', 'cases', ['user_id', 'created_at'], unique=False)
    op.create_table('fixes',
    sa.Column('created_by_user_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('instructions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.String(length=255), nullable=False),
    sa.Column('effort_level', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.String(length=255), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('partial_count', sa.Integer(), nullable=False),
    sa.Column('verified_success_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('reuse_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['profiles.id'], name=op.f('fk_fixes_created_by_user_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixes'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_notifications_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notification_user_read_created', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('reputation_events',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('reference_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_reputation_events_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reputation_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_reputation_events_idempotency_key'))
    )
    op.create_index('ix_reputation_user_created', 'reputation_events', ['user_id', 'created_at'], unique=False)
    op.create_table('reward_ledger',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=255), nullable=False),
    sa.Column('reference_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('claimable_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_reward_ledger_nonnegative_amount')),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_reward_ledger_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_ledger')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_reward_ledger_idempotency_key'))
    )
    op.create_index('ix_reward_user_created', 'reward_ledger', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_reward_user_status', 'reward_ledger', ['user_id', 'status'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('reward_notifications', sa.Boolean(), nullable=False),
    sa.Column('case_notifications', sa.Boolean(), nullable=False),
    sa.Column('contribution_notifications', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.String(length=255), nullable=False),
    sa.Column('leaderboard_opt_in', sa.Boolean(), nullable=False),
    sa.Column('analytics_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_user_settings_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('wallet_links',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('verification_nonce_hash', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_wallet_links_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_links')),
    sa.UniqueConstraint('wallet_address', name=op.f('uq_wallet_links_wallet_address'))
    )
    op.create_table('contributions',
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('case_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('fix_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('contribution_type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('verification_confidence', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('novelty_score', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('utility_score', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_contributions_case_id_cases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fix_id'], ['fixes.id'], name=op.f('fk_contributions_fix_id_fixes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_contributions_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contributions'))
    )
    op.create_index('ix_contribution_user_created', 'contributions', ['user_id', 'created_at'], unique=False)
    op.create_table('diagnosis_runs',
    sa.Column('case_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('problem_summary', sa.Text(), nullable=True),
    sa.Column('probable_cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('similar_case_count', sa.Integer(), nullable=False),
    sa.Column('model_provider', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('input_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_diagnosis_runs_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_diagnosis_runs_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis_runs'))
    )
    op.create_index('ix_diagnoses_case', 'diagnosis_runs', ['case_id'], unique=False)
    op.create_table('fix_attempts',
    sa.Column('case_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('fix_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_reported_result', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('steps_done', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_fix_attempts_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fix_id'], ['fixes.id'], name=op.f('fk_fix_attempts_fix_id_fixes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_fix_attempts_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fix_attempts'))
    )
    op.create_index('ix_attempt_case', 'fix_attempts', ['case_id'], unique=False)
    op.create_table('knowledge_attributions',
    sa.Column('fix_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('contributor_user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('ownership_share', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('attribution_type', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ownership_share > 0 AND ownership_share <= 1', name=op.f('ck_knowledge_attributions_valid_share')),
    sa.ForeignKeyConstraint(['contributor_user_id'], ['profiles.id'], name=op.f('fk_knowledge_attributions_contributor_user_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fix_id'], ['fixes.id'], name=op.f('fk_knowledge_attributions_fix_id_fixes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_attributions'))
    )
    op.create_table('case_fix_recommendations',
    sa.Column('case_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('diagnosis_run_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('fix_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('context_match_score', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('estimated_success_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_fix_recommendations_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnosis_run_id'], ['diagnosis_runs.id'], name=op.f('fk_case_fix_recommendations_diagnosis_run_id_diagnosis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fix_id'], ['fixes.id'], name=op.f('fk_case_fix_recommendations_fix_id_fixes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_fix_recommendations')),
    sa.UniqueConstraint('case_id', 'fix_id', name=op.f('uq_case_fix_recommendations_case_id'))
    )
    op.create_index('ix_recommendation_case_rank', 'case_fix_recommendations', ['case_id', 'rank'], unique=False)
    op.create_table('outcomes',
    sa.Column('case_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('fix_attempt_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('reported_result', sa.String(length=255), nullable=False),
    sa.Column('verification_method', sa.String(length=255), nullable=False),
    sa.Column('verification_confidence', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('verification_status', sa.String(length=255), nullable=False),
    sa.Column('before_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('after_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verification_summary', sa.Text(), nullable=True),
    sa.Column('observation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observation_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_outcomes_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fix_attempt_id'], ['fix_attempts.id'], name=op.f('fk_outcomes_fix_attempt_id_fix_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_outcomes_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes')),
    sa.UniqueConstraint('fix_attempt_id', name=op.f('uq_outcomes_fix_attempt_id'))
    )
    op.create_index('ix_outcome_case', 'outcomes', ['case_id'], unique=False)
    op.create_table('case_evidence',
    sa.Column('case_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('evidence_type', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcome_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_evidence_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], name=op.f('fk_case_evidence_outcome_id_outcomes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_case_evidence_user_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_evidence'))
    )
    op.create_index('ix_evidence_case', 'case_evidence', ['case_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_case', table_name='case_evidence')
    op.drop_table('case_evidence')
    op.drop_index('ix_outcome_case', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index('ix_recommendation_case_rank', table_name='case_fix_recommendations')
    op.drop_table('case_fix_recommendations')
    op.drop_table('knowledge_attributions')
    op.drop_index('ix_attempt_case', table_name='fix_attempts')
    op.drop_table('fix_attempts')
    op.drop_index('ix_diagnoses_case', table_name='diagnosis_runs')
    op.drop_table('diagnosis_runs')
    op.drop_index('ix_contribution_user_created', table_name='contributions')
    op.drop_table('contributions')
    op.drop_table('wallet_links')
    op.drop_table('user_settings')
    op.drop_index('ix_reward_user_status', table_name='reward_ledger')
    op.drop_index('ix_reward_user_created', table_name='reward_ledger')
    op.drop_table('reward_ledger')
    op.drop_index('ix_reputation_user_created', table_name='reputation_events')
    op.drop_table('reputation_events')
    op.drop_index('ix_notification_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('fixes')
    op.drop_index('ix_cases_user_created', table_name='cases')
    op.drop_table('cases')
    op.drop_table('audit_events')
    op.drop_table('account_deletion_requests')
    op.drop_table('profiles')
    # ### end Alembic commands ###

